Replace regexp with state machine, Fix #306
OpenHFT/Chronicle-Bytes pull request #315
Opened 2021-12-10 15:01 UTC by minborg

Most of the regular expression engines use backtracking to try all possible execution paths of the regular expression when evaluating an input, in some cases, it can cause performance issues, called *catastrophic backtracking* situations. In the worst case, the complexity of the regular expression is exponential in the size of the input, this means that a small carefully-crafted input (like 20 chars) can trigger catastrophic backtracking and cause a denial of service of the application. Super-linear regex complexity can lead to the same impact too with, in this case, a large carefully-crafted input (thousands of chars).

This PR replaces the use of regexp with a custom-made state machine, thereby preventing catastrophic backtracking.

2021-12-10 22:47 UTC, JerryShea requested changes
PropertyReplacer is not performance critical code. I would prefer we left this code as is

2021-12-13 12:10 UTC, minborg commented
The reason for this PR is not performance issues. Whether or not the procedure is 1-5 times faster or slower is not relevant. What is relevant is that crafted inputs (e.g. received over the wire or from a local file) can completely halt the application virtually forever. 

That is the reason for the suggested changes. 

Read more here: https://sonarcloud.io/organizations/openhft/rules?open=java%3AS5852&rule_key=java%3AS5852

2021-12-13 22:00 UTC, JerryShea commented
I just don't buy the cost/benefit of adding hundreds of lines of code to mitigate a problem which can happen when parsing configuration files

2021-12-13 22:24 UTC, nicktindall commented
I agree with Jerry on this, the linked vulnerability is an OWASP vulnerability, the "WA" being web application, if we were using this code to process inputs from the outside world in a process that absolutely had to remain live (like in a web server), I could see it being worth the added complexity, but if I understand it correctly this code only processes config files written by the in-house teams at startup, so:
1. It's unlikely they'd intentionally try to craft a bad input
2. If they did it would just prevent the app starting up, not catastrophically bring down a running mission critical app

In saying that, if we were doing a hot reload of config in a running process and the in-house team (or config file generator) accidentally produced a bad file (I'm not sure how feasible this is, it sounds like you'd need to do something pretty pathological to trigger this), it could be an issue.

Did we look at modifying the regex to reduce the possibility of back-tracking? (e.g. by putting a reasonable limit on the variable lenght or such?)

2021-12-14 09:01 UTC, RobAustin commented
@minborg can we have a chat to discuss the cost benefits of these changes? I feel we may be approaching the threshold where it's not worth making any further changes as the benefits are negligible.

2021-12-14 09:04 UTC, minborg commented
I agree with your arguments above. I have created a new PR with another way of solving the problem. See https://github.com/OpenHFT/Chronicle-Bytes/pull/320

2021-12-14 11:03 UTC, peter-lawrey commented
I think we should be reducing the complexity of the code, can we turn that rule off.

2021-12-14 12:39 UTC, minborg commented
This suggestion was dropped in favour of providing an updated regexp.

2021-12-14 12:39 UTC, closed without merging